#The maximal combat factor. See vanilla Enchantment Protection Factor.
#Range: 1 ~ 200
maxFactor = 100
#Scaling for (style) protection enchantments. See vanilla Enchantment Protection Factor.
#Range: 1 ~ 15
enchantmentScaling = 5
#Scaling for potion effects. Resistance (or Weakness) gained through potion effects will be scaled with this factor
#Range: 1 ~ 100
potionScaling = 50
#Weight for the essence item to spawn depending on the attack element of the mob. 0 disables this features. 1 is normal spawning rate.
#Range: 0.0 ~ 1.0
essenceSpawnWeight = 0.5

